### ISSUE TITLE
Arch Linux - the launcher downloads and extracts data but fails to install it

### ISSUE THREAD

**Issue by gardenappl** [FlashpointProject/launcher#104]
I ran into some trouble when installing Flash support for the [Flashpoint AUR package](https://aur.archlinux.org/packages/flashpoint-bin/). I believe it's using the latest Linux snapshot (2019-11-12)

I set up the Flashpoint directory, the launcher downloaded the required files into `<install dir>/Upgrade Data/<random uuid>/`, however after that point it did nothing. The launcher was stuck at "Installing files...".

I then looked at the [Linux Support guide](https://bluemaxima.org/flashpoint/datahub/Linux_Support): I created the folders `<install dir>/Data` and `<install dir>/Data/Platforms` and restarted the launcher. It then downloaded the files again, created the folder `<install dir>/Data/Playlists`, and got stuck again.

I worked around this issue by simply copy-pasting everything from `Upgrade Data` to `Data` manually, after a restart I was able to play games perfectly well.

**Comment by colin969** [comment]
Will check back with you after #120 is resolved.

**Comment by colin969** [comment]
AUR reponsibility has moved to a third party.
