### ISSUE TITLE
Prevent games from opening the web browser

### ISSUE THREAD

**Issue by Anuskuss** [FlashpointProject/launcher#136]
**Is your feature request related to a problem? Please describe.**
Certain games (e.g. Miniclip's Commando) open a new (empty) tab in my web browser upon starting a new game (not when launching). This is annoying since the tab is literally useless and opening the browser takes the focus away from the game.

**Describe the solution you'd like**
Redirect the call (maybe to a custom, one page window similar to the popup window in Chrome) or outright block it. I guess the game tries to open miniclip.com or something but it's irrelevant either way.

**Comment by colin969** [comment]
This would be an issue with the supporting tech (E.G Flash Player) so isn't solvable in the launcher. May be preventable in the future through projects like Ruffle or by running it as an embed via Basilisk.

**Comment by Anuskuss** [comment]
Isn't there already a redirector of some sorts integrated in Flashpoint? Why wouldn't that apply here?

**Comment by colin969** [comment]
The redirector was only a proxy (to another proxy) for web requests.

If it's opening your browser than it's explicitly asking to open the URL in browser, not making a web request.
