### ISSUE TITLE
Game ZIP integration + downloads

### ISSUE THREAD

**Issue by Seirade** [FlashpointProject/launcher#157]
**Is your feature request related to a problem? Please describe.**
For games served to Infinity, we need game zip integration, along with a content server to deliver them. These come in the form of `<uuid>.zip`.

**Describe the solution you'd like**
Launcher behavior would have to change, such that it first checks to see if `<uuid>.zip` exists in the directory where game zips are stored. If not, it would then download the game zip with a reliable method, such as wget or "IEDL" by @XXLuigiMario. The built in PHP webserver is not suitable, since it's unable to handle large files. Once finished, launch the game using FPMount (also by @XXLuigiMario).

The other part of integration is to add all functionality provided by "bluezip" to the Launcher itself. There also needs to be a way to easily edit game zips, in order to do content edits. A good way would be to provide an "Edit Curation" button to the Curate tab (or a context menu item when right-clicking an entry). This would load the curation to a separate screen similarly to the "Load Archive" button, only it would grab the contents from the zip, and allow you to browse the contents as normal. On this screen, since there's no metadata editing, you would only have the options to Save (which replaces the game zip after confirmation), Save As (similar to exporting), and a 3rd button that does both. Maybe in the future a Submit button for automatically uploading to a submissions website. Ideally, game zips should be treated in a similar way to a Word Document. Both are zip files, but require a proper editor to work with.

**Describe alternatives you've considered**
The current workaround relies on creating Additional Application entries for every zipped game, so that the Launcher knows to play them using FPMount. This doesn't scale well when it's required by the maintainer of the master build to make those AddApps.

**Additional context**
N/A

**Comment by colin969** [comment]
Offline contributions in #191
