### ISSUE TITLE
Improve curation debugging experience

### ISSUE THREAD

**Issue by gyorokpeter** [FlashpointProject/launcher#158]
Currently when I'm making a curation and want to check the logs, I have to switch back and forth between the Logs and the Curations tab. This is especially inconvenient because the Curations tab will lose the last selection and scroll status, meaning not only do I have to click on the button, but also select the curation and scroll down to the bottom to find the run button again.

Possible solutions:
- Make the curations tab remember the selected curation and scroll status
- Ability to pop out the Logs tab to a separate window such that I don't have to switch back and forth

**Comment by ColdIce1** [comment]
Option for clearing cache would also be nice!
