### ISSUE TITLE
Playlists - Games vs. Animations

### ISSUE THREAD

**Issue by reklawyksekul77** [FlashpointProject/launcher#161]
Currently you can import a playlist.json file into either the Games or Animations tab and there is no control on whether that playlist is actually for games or just animations.  

There should be some sort of control that prevents a playlist that was made in the animations tab from being imported into the games tab and vs versa.

**Comment by colin969** [comment]
This is somewhat intentional. Eventually, the libraries will be merged into one screen. Animations and Games should be able to co-exist in a playlist.
