### ISSUE TITLE
Game file integrity verification

### ISSUE THREAD

**Issue by deluxghost** [FlashpointProject/launcher#166]
**Is your feature request related to a problem? Please describe.**

Sometimes I cannot realize the game files are missing or broken, because the game may not be broken entirely, just behave weird.

**Describe the solution you'd like**

We need 2 parts:

* Verify files after download and retry.
* A feature like Steam has: manually verify the integrity of the game files. If it's a multi assets game, provide an option to verify all/downloaded files (and list all files that haven't been downloaded?).

**Describe alternatives you've considered**

no :(

**Additional context**

no

**Comment by colin969** [comment]
This won't be possible until the Game Zips implementation is further along

**Comment by deluxghost** [comment]
I know, consider this as a backlog
