### ISSUE TITLE
Missing strings on Crowdin

### ISSUE THREAD

**Issue by arcturus108** [FlashpointProject/launcher#172]
Some strings are missing on the Crowdin project. Here is a list of all I managed to find:
developer -> forceGameMetaSync
developer -> Server
developer -> Legacy Webserver
categories -> Name
categories -> Description
tags -> Name
tags -> Aliases
tags -> Category

The version data text is also missing (in about -> version) but I'm not sure on the feasibility of implementing that one.

Screenshots: https://imgur.com/a/P5CttCU

**Comment by colin969** [comment]
The meta sync string is unused at the moment.

Server and Legacy Webserver are defined in /Data/services.json

The others I'll take a look at soon

**Comment by deluxghost** [comment]
there is a 'forceGameMetaSync' button in the launcher actually, I think it needs to be added to the json.

**Comment by colin969** [comment]
Fixed with https://github.com/FlashpointProject/launcher/commit/716d00ed8e12eca2ab28212f6b7e29606e2c906a
