### ISSUE TITLE
Clicking off screen

### ISSUE THREAD

**Issue by webdesires** [FlashpointProject/launcher#174]
Several games I play use the mouse for direction / attacking.

The problem is these games dont show the mouse cursor, but even so... if you happen to click outside the game window you end up clicking on anything outside the game which is really annoying.

There should be some way to either capture the mouse and stop ig leaving the game window, or full-screen play options.

**Comment by deluxghost** [comment]
this workaround might help? http://quickwebgems.blogspot.com/2013/12/cursor-lock-keep-mouse-within.html

**Comment by colin969** [comment]
This is an issue related to tech used in Flashpoint as a project, not software, please consider using the discord server instead.

https://bluemaxima.org/flashpoint/discord
