### ISSUE TITLE
[BUG] searching tags in playlists

### ISSUE THREAD

**Issue by supremebloxboy** [FlashpointProject/launcher#177]
**Describe the bug**
when you search with a tag in a playlist, it shows games that aren't in that playlist.
also shows duplicate games.

**To Reproduce**
1. goto any playlist(eg. Favorites)
2. search with a tag(eg. tag:Action)

**Expected behavior**
when you search a tag in a playlist, it should show only games that are in that playlist,

**Screenshots**
see screenshot, i added text in red, please read
![8c2196dc903b44325e0811acac2a2aea](https://user-images.githubusercontent.com/58655454/104116284-bf422d00-52dc-11eb-8fb3-4499a0fe6910.png)

**Desktop (please complete the following information):**
Windows 10
Flashpoint 9.0 "Glorious Sunset"

**Additional context**
appearently after writing this bug report, its come to my attention that this bug also works with just word searches. if you goto a playlist(eg. Brawlers battles), and search for a game(eg. dad), it shows "dad 'n me"(expected), but it also shows "Mouse FX 2"(Not expected)

**Comment by colin969** [comment]
Depends whether you'd call it fixed, Playlists no longer abide by filtering.
