### ISSUE TITLE
Tap'Touche Garfil

### ISSUE THREAD

**Issue by EngrishGuysTaig** [FlashpointProject/launcher#182]
So for a school computer, we need this Flash software(Made in Quebec, France ?) named 
TapʼTouche Garfield
But flash is dead so i wonder if it possible to launch 
TapʼTouche Garfield using Flashpoint

Thank you, Please respond if you can !

**Comment by colin969** [comment]
This is a question about flashpoint as a project, not a software, please ask in the Discord.

https://bluemaxima.org/flashpoint/discord/
