### ISSUE TITLE
Game thinks it is not running from the original website!

### ISSUE THREAD

**Issue by Joe23232** [FlashpointProject/launcher#187]
I am playing _Gemcraft Chapter 0_ and the game thinks that I am not playing it on the original website as shown in the image below.

![image](https://user-images.githubusercontent.com/34926497/106375632-cf33c500-63e1-11eb-9da3-b6d361847323.png)

I thought Flashpoint is supposed to create an internal server to trick the game into thinking it is running on the original server or am I missing something?

**Comment by tyefyedye** [comment]
This issue is related to how the game is run in Flashpoint, not the launcher itself.

Please report this bug in the Flashpoint discord server.
https://bluemaxima.org/flashpoint/discord/

**Comment by Joe23232** [comment]
Ok sure, thanks
