### ISSUE TITLE
Logo Set images not centering correctly [BUG]

### ISSUE THREAD

**Issue by 40411** [FlashpointProject/launcher#198]
**Describe the bug**
The logo previews for the Logo Sets in the Config tab will not be centered if the image file isn't perfectly square, instead they will shift to the top left.

**To Reproduce**
1. Go to the config tab
2. Scroll down to Visuals
3. On Logo Set observe the previews for the default logos.

**Expected behavior**
The logos should center in their positions in case the image isn't square.

**Screenshots**
![ezgif-6-2b85e59c22ae](https://user-images.githubusercontent.com/80294264/110396799-8c13e400-8068-11eb-8960-3d537235373e.gif)
DIfference between current visuals and a mockup with centered logos.

**Desktop:**
 - OS: Windows 10
 - Flashpoint Infinity Version 9.0

**Comment by Felix-Puetz** [comment]
@colin969 I think we can close this issue then :)
