### ISSUE TITLE
Ability to hide thumbnails for (extreme) games

### ISSUE THREAD

**Issue by muzikbike** [FlashpointProject/launcher#202]
Would have three settings: off, extreme only (could potentially depend on tag filters instead), or all.

This would also prevent any of the affected games' two images from being downloaded to the device until specifically requested.

For affected games, the image in the main list would be replaced with some sort of placeholder image (there's a Wikipedia extension that replaces all images with a Battenburg pattern, which this could also do), and the example gameplay image would also be replaced with this, with a button in the middle that, when clicked, after a confirmation window is checked, displays both associated game images.

**Comment by colin969** [comment]
Screenshots can be hidden, logos will not be (they should be fine anyway)

**Comment by muzikbike** [comment]
Not necessarily, if #197 is anything to go by
