### ISSUE TITLE
In-launcher way to view games that have been played/downloaded

### ISSUE THREAD

**Issue by muzikbike** [FlashpointProject/launcher#211]
Currently the only options are checking what game files/folders have already been downloaded, which is less than convenient, or manually adding each played game to Favourites, which is more labour-intensive that it really needs to be and isn't helpful if it's in use for something else.

**Comment by HonzaSTECH** [comment]
Suggested the same in #210

**Comment by VFDan** [comment]
https://github.com/LeShaps/FPL-History would do the job but doesn't work in Infinity yet.

**Comment by ColdIce1** [comment]
Why this issue should be voted for:
* Keeping track on what games you have played is annoying in general.
*  Continuing playing a game that you forgot the title of could require a bunch of effort.


Suggestions:
Make the launcher save a timestamp of when you launch each game. This timestamp could be used to order the games after "most recently played".
There should probably be some systems for the following:
* Clear all timestamps (should probably show a "Are you sure?" popup)
* Remove a single timestamp (maybe several at a time too?)
* A way to enable/disable the saving of timestamps (like incognito mode)

(Saved from Trello https://trello.com/c/O8CW84Mf/50-remember-recently-played-games )
