### ISSUE TITLE
Motivate Curators by keeping their names

### ISSUE THREAD

**Issue by HonzaSTECH** [FlashpointProject/launcher#213]
**Is your feature request related to a problem? Please describe.**
I feel like a very big part of Trial Curators stop contributing to the project after a while because they already archived what they wanted and they feel like they aren't getting any credit. Some of them might hope to appear in the Credits one day, but the fact that there are no clear requirements to get the role makes this goal feel uncertain and inaccessible. And so, they leave the project.

**Describe the solution you'd like**
I suggest the addition of a new metadata field: `Curator` or `Curated by`. When curating, the curator would simply write their nickname into it and they would be credited as the one who archived that game in the launcher. 

**Describe alternatives you've considered**
This would also be great for another reason. Many curators like to create playlists of games they curated, which might be very time-consuming. With the `Curator` field, all they would need to do is a simple search.

**Additional context**
Any games that were already curated would have this field empty (it could be set to something like `Nameless champ`). However, this could be theoretically fixed automatically by searching for who posted the given curation in `#flash-game-curations`, `#other-games-curations` or `#animations-curations` and filling the field with their Discord nickname. Another option is leaving this to pending fixes. However, there is a risk that some dishonest users might try to attribute themselves as curators of games, that they didn't curate. But I think that our community is mature enough for this.

This field should be optional because some curators might wish to stay anonymous (especially in the case of NSFW curations).

**Comment by prostagma-fp** [comment]
Not listing the reasons here, but crediting curators is a can of worms for easier deletion requests. FPFSS already does his fine for those submitted on the system.

**Comment by HonzaSTECH** [comment]
Isn't it like only the original creators of the games can request their deletion, not the curators?
