### ISSUE TITLE
Split 3D objects from Games?

### ISSUE THREAD

**Issue by muzikbike** [FlashpointProject/launcher#215]
There's quite a lot of these and while they're currently grouped with games due to being interactive I'd say they should probably be split into a separate tab like animations are.

**Comment by muzikbike** [comment]
As to make sure a "3D Object" can be defined different from a game and animation while at the same time avoiding edge cases where possible, we can define the following criteria:

- The application has no interactivity or its only interactivity is to start it and it has no further interactivity: Animation
- The application has interactivity, but exclusively for rotation and flipping of a 3D object: 3D object
- The application has interactivity beyond these two cases: Game

**Comment by colin969** [comment]
This is a distinction for Flashpoint tagging as a project, not a software.
