### ISSUE TITLE
Standardize level databases for games with level editors

### ISSUE THREAD

**Issue by muzikbike** [FlashpointProject/launcher#216]
Currently they tend to use the pages from the site they originally came from but this is suboptimal and buggy. Having a standard Flashpoint way of presenting them, perhaps with the ability to submit more custom levels to the database and have ratings and public tracked highscores on them, and/or for verified former users to edit/delete levels, might be interesting.

**Comment by lino-levan** [comment]
As someone who's worked a bit with the whole Super Mario 63 Mod for level preservation, these things really need to be done on a game-by-game basis. Besides the issue with server hosting, I believe it is currently infeasible to try to standardize an online database among multiple games.
