### ISSUE TITLE
Adding a test framework

### ISSUE THREAD

**Issue by Mordax** [FlashpointProject/launcher#22]
There's a lack of tests in FPL, so I've been investigating what we could use. So far, I think [Jest](https://jestjs.io/) suits our needs - but since the project is written in Typescript, the recommendation was to install [ts-jest](https://github.com/kulshekhar/ts-jest), which supports the language + type checking. 

Some notes from researching:
- A lot of the testing needs to be [mocked](https://jestjs.io/docs/en/mock-functions) due to a lot of the code being void functions
- We will probably need [react-test-renderer](https://reactjs.org/docs/test-renderer.html) to test the React code
- We will probably need [Spectron](https://electronjs.org/spectron) for Electron specific tasks

I will open a PR shortly with the configs and an example test function.

**Comment by TBubba** [comment]
Looks good!

But before I pull, could you make the folder structure inside ``tests`` mirror the folder structure inside ``src`` (so the test files are easier to find, and so no filename collisions can occur)?

**Comment by Mordax** [comment]
Whoops, I didn't realize that I forgot the `main` folder lol.

**Comment by TBubba** [comment]
Looks like I forgot to close this. Whoops
