### ISSUE TITLE
[BUG] Node-Tree-Kill does not work on macOS

### ISSUE THREAD

**Issue by ModdedGamers** [FlashpointProject/launcher#220]
**Describe the bug**
As described in pkrumins/node-tree-kill#28, tree-kill does not work on macOS.

**To Reproduce**
This is currently hard to reproduce, as it only happens on macOS, and >99% of flashpoint activity is on Windows. However, in my work porting flashpoint to mac, this bug comes up.

**Expected behavior**
I expected flashpoint to kill the process.

**Screenshots**
See the logs here: https://logs.unstable.life/log?id=4BVSXUSS

**Desktop (please complete the following information):**
 - OS: macOS
 - Flashpoint Version 10, built from branch release/10.0.0 latest commit
 - Log text: See screenshots.

**Additional context**I and another developer, `ColdIce#0001` on discord, suggest using [tmbr](https://github.com/benjaminwoods/tmbr) as a replacement, as it is more recently updated and seems to have a simpler syntax than tree-kill.

**Comment by LindirQuenya** [comment]
It seems that I can't use GitHub's built-in "assign" feature, so I'll use a comment as a substitute.

This is what I'm currently working on.
