### ISSUE TITLE
[BUG] Extreme meta field exported in the meta.yaml on Core

### ISSUE THREAD

**Issue by Soulsderfuchs** [FlashpointProject/launcher#222]
**Describe the bug**
Since the extreme tag filter system was implemented the extreme toggle was disabled on the curate tab paving the way to the launcher detecting if a curation is extreme by their tags alone , but now even when exporting a curation the meta file generated contains the extreme field set to no ,interfering with the new submission system 

**To Reproduce**
1. Go to 'Flashpoint Core 10.0'
2. Click on 'Create a new curation ,add extreme tags ,export said curation'
3. Scroll down to 'The new created zip folder of the curation ,inside the meta.yaml file in it it should say Extreme: No'

**Expected behavior**
Exporting the file with Extreme : Yes when a extreme tag is detected

**Screenshots**
![7zFM_B0uJKj1wSY](https://user-images.githubusercontent.com/59575350/122656546-27652c80-d121-11eb-911a-74adf9cbeded.png)
**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Flashpoint Version [10.0]
 - Log text (if relevant)

**Additional context**
This field could be erased altogether now ,but I think it should stay for legacy reasons maybe

**Comment by colin969** [comment]
Issue with the submissions site, left alone for legacy reasons.
