### ISSUE TITLE
Hiding the Original Description and Notes if they're empty

### ISSUE THREAD

**Issue by okhrvhzu1** [FlashpointProject/launcher#229]
**Is your feature request related to a problem? Please describe.**
Not a problem as much as UI idea
I lot of game have the OG desc and Notes empty, and they take so much space (Because each of them have their own space and margin)
I feel like removing them will result in a cleaner UI... but may affect the consistency of the UI(?)

**Describe the solution you'd like**
If they are empty hide them

**Describe alternatives you've considered**
N/A

**Additional context**
Here is a screenshot of the current the game tab:
![Screenshot_1](https://user-images.githubusercontent.com/50371589/124527515-66c49600-de0e-11eb-9877-ab3450cfe4b1.png)

By editing the HTML, this is what i vision it to be:
![Screenshot_2](https://user-images.githubusercontent.com/50371589/124527536-7fcd4700-de0e-11eb-8278-a40f10a46ae7.png)

**Comment by Felix-Puetz** [comment]
seems to be fixed already

![image](https://user-images.githubusercontent.com/50131232/126682251-d8df6b34-4236-48f5-91b0-a325443d4197.png)
