### ISSUE TITLE
Different icons for different levels of extreme

### ISSUE THREAD

**Issue by muzikbike** [FlashpointProject/launcher#230]
Currently there's just 18, but there's other levels of extremeness content that may benefit from the implementation of dedicated icons. For example, not-at-all extreme content could have a dedicated icon, as could something considered fitting for 13+ users which wouldn't warrant a complete 18+.

**Comment by colin969** [comment]
Age ratings aren't really a consideration at the moment, but it's free to be looked at in the future.
