### ISSUE TITLE
[BUG] Preferences are wiped in certain situations

### ISSUE THREAD

**Issue by n0samu** [FlashpointProject/launcher#239]
**Describe the bug**
The `preferences.json` file will sometimes be wiped (the file will become empty). Because of #238, the launcher will be unable to open at all once the preferences are wiped. I am not sure when exactly this problem happens, but it has been reported in our Discord by multiple people. Apologies for the lack of detail; if anyone can reproduce the issue, please comment here. In general, people have reported that closing the launcher while it is frozen or lagging will cause this problem.

Souls reports that on his computer, he can follow these steps to reproduce the issue:
1. Type `tag:` in the main search bar and continue typing to get tag suggestions
2. Click one of the tag suggestions. The launcher will freeze for a moment.
3. Close the launcher while it's frozen.
4. The preferences will be wiped

**Comment by Soulsderfuchs** [comment]
You can induce this lagged/loading behavior on newer computers by quickly switching the extreme content toggle on and off until it starts toggling on it's own then searching a tag suggestion on the same config page which brings the laucher to a blank state momentarily while processing, this is the same state users with older computers have reported seeing as it would "freeze" on them 
![Flashpoint_n0L9TChGPH](https://user-images.githubusercontent.com/59575350/132081387-4b0c117d-840f-4f74-ba37-60a8c25cc239.png)

If you close the launcher in this state it will always make the preference file 0kbs, preventing the launcher from opening again until the file is deleted or replaced with a stock one
![explorer_swdwv8u6Rl](https://user-images.githubusercontent.com/59575350/132081429-84bcc299-92dc-4eec-aae2-1eb30bdba986.png)

**Comment by n0samu** [comment]
This problem is still occurring in the latest Flashpoint release. Please reopen this issue.
