### ISSUE TITLE
Make the notes and original description fields expandable

### ISSUE THREAD

**Issue by MagnificentNoodle** [FlashpointProject/launcher#241]
**Is your feature request related to a problem? Please describe.**
Some notes and original descriptions can contain quite a lot of text and as a result push the screenshot and other buttons all the way down in the sidebar, usually off-screen. This can be frustrating as this sometimes adds a lot of scroll just to view a screenshot or access the game data browser.

**Describe the solution you'd like**
My proposed solution would be to make the notes and original description fields expandable by adding a "View more" button to each field when the text gets to a certain length. (see YouTube's video description boxes for implementation example)

**Describe alternatives you've considered**
An alternative would be to move one of the fields, or both, below the screenshot. But this is not preferred as it would break up the metadata and potentially push useful notes down where they wouldn't draw as much attention.

**Comment by colin969** [comment]
Implemented a suitable solution in 
18c47f3
