### ISSUE TITLE
[BUG] In Animation tab the sidebar shows the string no game selected if such

### ISSUE THREAD

**Issue by dot-mike** [FlashpointProject/launcher#273]
**Describe the bug**
Sidebar in animation-tab shows the string `No game selected` when in fact it should show `No animation selected`

**To Reproduce**
1. Start Flashpoint.exe
2. Click on Animationt-tab
3. See error in the right-hand sidebar

https://trello.com/c/o48dl3vA/178-if-youre-in-the-theatre-tab-and-havent-selected-an-animation-the-sidebar-says-no-game-selected

**Comment by colin969** [comment]
Fixed in 4286bcb337e13b90b4da3b14ae6b682923f92926
