### ISSUE TITLE
There are no games

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [FlashpointProject/launcher#279]
**Describe the bug**
There are no games in the launcher

**To Reproduce**
install the linux version and bam, no games

**Expected behavior**
there should be a list of games 

I am using ubuntu 21.04

**Comment by LindirQuenya** [comment]
Cannot reproduce on 21.10 - please follow the directions [here](https://bluemaxima.org/flashpoint/datahub/Linux_Support#Manual_Installation_.28for_advanced_users.29) for a working installation. Setting the Flashpoint directory (in config) may also be needed.

**Comment by Etaash-mathamsetty** [comment]
no longer using ubuntu, but I am no longer experiencing this issue either so i'm closing
