### ISSUE TITLE
Set a minimum size on the main window

### ISSUE THREAD

**Issue by spencerthayes** [FlashpointProject/launcher#288]
I was able to resize the main window so much, that I almost wasn't able to see any of the content and it was difficult to resize it back to a reasonable size. 

![image](https://user-images.githubusercontent.com/16262389/142770216-e5bdbabb-e66a-4325-a758-d30ed5f4c9e2.png)

I think it would be beneficial to set a minimum size to the main window. For example 400x300.

**Comment by colin969** [comment]
Addressed in 2fe7fb7bcb759ed7290c2cc6f125fbcba0e89fca
