### ISSUE TITLE
Flashpoint 10.1 super slow

### ISSUE THREAD

**Issue by SquareCereal724** [FlashpointProject/launcher#289]
Flashpoint 10.1 is unusably slow.
QEMU uses up too much ram.
deleting qemu fixes the slowness but you cant use flashpoint properly
please change it back to how flashpoint 9 was (or at least make it a setting)

**Comment by LindirQuenya** [comment]
QEMU using up RAM is a problem for [flashpointvm](../../flashpointvm).
If you want a lighter-weight image, please grab the latest release from there, and save it as (FP)/Server/alpine.qcow2.
You will need to modify arguments of the Apache Webserver entry in Data/services.json to `["-m", "128", "-net", "nic,model=virtio-net-pci", "-net", "user,hostfwd=tcp:127.0.0.1:22500-:80", "-qmp", "tcp:127.0.0.1:4444,server,nowait", "-qmp", "tcp:127.0.0.1:4445,server,nowait", "-drive", "file=alpine.qcow2,if=virtio", "-serial", "stdio", "-loadvm", "quick", "-display", "none"]`, as detailed in [this pull request.](../../flashpointvm/pull/1)
This won't revert back to FP 9, but it will improve the RAM usage.

**Comment by SquareCereal724** [comment]
is there any disadvantages to doing this?

**Comment by LindirQuenya** [comment]
None that I know of. If you run into any, please [open an issue](https://github.com/FlashpointProject/flashpointvm/issues) with flashpointvm.

**Comment by SquareCereal724** [comment]
so why doesnt it do that by default?

**Comment by LindirQuenya** [comment]
Because these changes are more recent than the most recent release. The new flashpointvm image will be in the next release. We didn't include it in the last release because it didn't exist when the last one came out.
As for why we don't auto-update, because it would be too much of a pain to setup and maintain.
