### ISSUE TITLE
Disable hardware acceleration by default

### ISSUE THREAD

**Issue by n0samu** [FlashpointProject/launcher#295]
**Is your feature request related to a problem? Please describe.**
A lot of users have trouble running Flashpoint Launcher with hardware acceleration. That's why we created this Extended FAQ entry: https://bluemaxima.org/flashpoint/datahub/Extended_FAQ#LauncherBlackScreen

**Describe the solution you'd like**
I think the launcher should be run with hardware acceleration disabled by default. This will allow the launcher to work on a wider range of computers without making users jump through hoops.

**Describe alternatives you've considered**
In my own tests, disabling hardware acceleration didn't really seem to impact launcher performance. But if performance is a concern, I guess there should be a setting on the Config tab to enable hardware acceleration (and disable it by default). Or maybe the launcher could somehow detect when it fails to render correctly and automatically turn off hardware acceleration, but keep it enabled by default?

**Additional context**
Often, this problem manifests as a fully black/grey screen. But sometimes users get even more interesting glitches like this:
![image](https://user-images.githubusercontent.com/71368227/151309372-2fd588e8-325b-4335-ad78-0ff8fc6613b0.png)
Disabling hardware acceleration fixes these as well.

**Comment by LindirQuenya** [comment]
It's not a hardware acceleration bug, it's a hardware acceleration feature! Just look at those pretty patters.
More seriously, I think that the easiest way to handle this is by changing the launch script/lnk to include the `--disable-gpu` option.

**Comment by n0samu** [comment]
That would only work for people who actually use the Start Flashpoint shortcut. We can definitely do that if people agree we should, though.

**Comment by colin969** [comment]
Changed in 9b6aa9b818fb72ad18642cc9715efd4d771bbf9b
