### ISSUE TITLE
[BUG] MacOS: Launcher cannot load its own config and preferences

### ISSUE THREAD

**Issue by n0samu** [FlashpointProject/launcher#296]
**Describe the bug**
On MacOS, the launcher is unable to load its own preferences/config when opened directly because it tries to read the config.json file from its working directory. On MacOS, the working directory of the executable is inside of the app package, which is not where the config,json file is stored. Also, relative Flashpoint Paths (set in the Config tab) are interpreted as relative to the current working directory, rather than being relative to the directory where the app package is located (the main Launcher directory). 

I believe that this problem is caused by using `app.getPath('exe')` to get the path to the launcher's containing folder. `app.getAppPath()` should be used instead because it has the correct behavior on all platforms: https://github.com/electron/electron/blob/main/docs/api/app.md#appgetapppath

**To Reproduce**
1. Download the Flashpoint Infinity for Mac Beta: https://bluemaxima.org/flashpoint/datahub/Mac_Support#Latest_Package
2. On a Mac, unzip the file and double-click the Flashpoint Launcher app. You'll see that Flashpoint does not work properly, as described in detail above,

**Expected behavior**
Flashpoint should try to read its config file from the main Launcher folder, not from its app package. And relative Flashpoint Paths should be relative to the Launcher directory, as they are on Windows.

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by foxtrotdev** [comment]
The problem still persists. Solution: Please move extracted Flashpoint archive to `Applications` folder and execute the launcher from mentioned folder. Now it will work.

**Comment by n0samu** [comment]
This is caused by Gatekeeper quarantining the application. You need to either use curl to download Flashpoint or remove the quarantine attribute from the downloaded tar.xz file before extracting. And you need to extract the tar.xz file using Archive Utility, not a third-party program. This info is from the [Mac Support wiki page](https://flashpointarchive.org/datahub/Mac_Support).

**Comment by foxtrotdev** [comment]
OK, I see. Extracting took me more time but finally Archive Utility extracted it with success. Thanks!

**Comment by n0samu** [comment]
Next time please do not delete your messages. It makes it impossible for future readers to follow the conversation.
