### ISSUE TITLE
[BUG] Flashpoint does not launch

### ISSUE THREAD

**Issue by Martmists-GH** [FlashpointProject/launcher#306]
**Describe the bug**
running the `flashpoint` script does not launch flashpoint

**To Reproduce**
1. Install flashpoint as described here: https://bluemaxima.org/flashpoint/datahub/Linux_Support
2. run `../launcher/flashpoint`
3. Nothing happens, not even an error.

**Expected behavior**
Flashpoint launches or gives an error

**Screenshots**
![Screenshot_20220301_153230](https://user-images.githubusercontent.com/16361449/156187970-7144c12e-deaa-4ada-88ba-3bf09cb5da93.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux x64
 - Flashpoint Version: 10.1.1
 - Log text: N/A

**Comment by n0samu** [comment]
This is not a bug, you need to install Flashpoint's dependencies as explained here: https://bluemaxima.org/flashpoint/datahub/Linux_Support#Dependencies
Please join the #flashpoint-mac-linux-help channel on our Discord server if you have any more issues

**Comment by Martmists-GH** [comment]
All those dependencies are installed.

**Comment by n0samu** [comment]
What happens when you run the `php` and `qemu-system-i386` commands directly from the terminal? You need to make sure those commands are recognized

**Comment by LindirQuenya** [comment]
Please ensure that the directories with the binaries are on PATH when launched by `/bin/sh`.

**Comment by Martmists-GH** [comment]
```sh
#!/bin/sh
cd /home/mart/opt/flashpoint/launcher
/home/mart/opt/flashpoint/launcher/flashpoint-launcher
killall php
killall qemu-system-i386
```
It seems to use the path directly so it should work either way, but just in case I've double-checked:
```
$ which git 7z tar wine wget php qemu-system-i386
/usr/bin/git
/usr/bin/7z
/usr/bin/tar
/usr/bin/wine
/usr/bin/wget
/usr/bin/php
/usr/bin/qemu-system-i386
```

**Comment by Martmists-GH** [comment]
It seems to randomly have decided to work after several reboots.
