### ISSUE TITLE
[BUG] meta.txt/meta.yaml inside a curation archive's content folder is detected as the main meta file

### ISSUE THREAD

**Issue by n0samu** [FlashpointProject/launcher#308]
**Describe the bug**
When a curation archive (7Z) is loaded onto the Curate tab, and the curation contains a file named meta.txt or meta.yaml somewhere within the content folder, the folder containing that meta.txt or meta.yaml file is detected as the main curation folder. Thus the curation fails to load and all files outside of this subfolder of the content folder are discarded entirely.

**To Reproduce**
1. Download this curation: https://cdn.discordapp.com/attachments/569426826691346444/949040251131797544/sx7oj40yewe6w2kqzsiyv7d2pj9647bmy0bpm40donobk9jmm6zr0swfa3f8wbxy.7z
It contains a meta.txt file in the `content\www.nyphilkids.org\dressingrooms` folder.
2. Open Flashpoint Core, click the Curate tab, and click "Load Archive"
3. Select the downloaded curation. It will fail to load properly.
4. Click "Open Folder" at the bottom of the curation and notice that the only files included in the loaded folder are those that were inside of the ` content\www.nyphilkids.org\dressingrooms` subfolder. And the launcher attempted to convert the meta.txt file into a meta.yaml file, which also failed (since it is not actually a curation meta file).

**Expected behavior**
The launcher should have detected the meta.yaml file inside the main curation folder as the curation's meta file.

**Screenshots**
(Top-left is the original curation folder, bottom-left is the loaded curation folder, right is the logs)
![image](https://user-images.githubusercontent.com/71368227/156677503-ffc8d162-2164-4163-a403-4ec5fb108e62.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Flashpoint Version: Core 11
 - Log text (if relevant)

**Additional context**
A properly structured curation has one of the following two structures inside the 7Z or ZIP file:
```
│   logo.png
│   meta file
│   ss.png
│
└───content
    └───content files
```
or
```
└───Folder with arbitrary name
    │   logo.png
    │   meta file
    │   ss.png
    │
    └───content
        └───content files
```
Curations exported from the Curate tab always use the latter format, with the name of the top-level folder being a random UUID. In older curations that use the latter format, the top-level folder is usually named according to the title of the game.

**Comment by LindirQuenya** [comment]
Found the cause: src/curate/importCuration/getRootPath() is implemented wrong. Expect a PR soon.
