### ISSUE TITLE
[BUG] Flash player crashes in wine

### ISSUE THREAD

**Issue by Martmists-GH** [FlashpointProject/launcher#310]
**Describe the bug**
Flash player crashes when launching any game

**To Reproduce**
1. Hit "Play"
2. Crash

**Expected behavior**
The game launches

**Screenshots**
<details>
<summary>crash report</summary>
<code><pre>
Unhandled exception: unimplemented function urlmon.dll.414 called in 32-bit code (0x7bc2a3c0).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7bc2a3c0 ESP:058ef674 EBP:058ef6d8 EFLAGS:00000202(   - --  I   - - - )
 EAX:0000019e EBX:058ef680 ECX:7121d276 EDX:712b648c
 ESI:0140f7f0 EDI:058ef714
Stack dump:
0x058ef674:  712b9a78 00000000 00000000 80000100
0x058ef684:  00000001 00000000 7bc2a3c0 00000002
0x058ef694:  712b648c 0000019e 7122bac9 ffffffff
0x058ef6a4:  0140fc9c 0140f7f0 00000000 7121c9a1
0x058ef6b4:  7121822c 00000000 00000000 ffffffff
0x058ef6c4:  00000000 00000000 058ef6ec 058ef6e4
Backtrace:
=>0 0x7bc2a3c0 A_SHAFinal+0xaa10() in ntdll (0x058ef6d8)
  1 0x0035003c (0x058ef77c)
  2 0x7121df3c EntryPoint+0x1c6d7() in wininet (0x058ef8c8)
  3 0x7121cbc5 EntryPoint+0x1b360() in wininet (0x058ef92c)
  4 0x712438d2 EntryPoint+0x4206d() in wininet (0x058ef950)
  5 0x7129192e CreateMD5SSOHash+0x15c41() in wininet (0x058ef9a8)
  6 0x0075ea0f _WinMainSandboxed@20+0x2f1144() in flashplayer_32_sa (0x058efeb4)
  7 0x0075f416 _WinMainSandboxed@20+0x2f1b4b() in flashplayer_32_sa (0x058eff30)
  8 0x7b62d0d0 ActivateActCtx+0x227c0() in kernel32 (0x058eff48)
  9 0x7bc57cb7 A_SHAFinal+0x38307() in ntdll (0x058eff5c)
  10 0x7bc58370 A_SHAFinal+0x389c0() in ntdll (0x058effec)
0x7bc2a3c0 ntdll+0x2a3c0: subl	$4,%esp
Modules:
Module	Address			Debug info	Name (58 modules)
PE	00400000-013b6000	Export          flashplayer_32_sa
PE	014d0000-01e09000	Deferred        shell32
PE	02510000-0252c000	Deferred        imm32
PE	027a0000-027a2000	Deferred        usp10
PE	054f0000-055b7000	Deferred        winmm
PE	10000000-1001e000	Deferred        flashpointproxy
PE	61500000-6152f000	Deferred        iphlpapi
PE	61740000-61783000	Deferred        advapi32
PE	62b80000-62b88000	Deferred        api-ms-win-core-localization-l1-2-1
PE	62fc0000-6304e000	Deferred        rpcrt4
PE	631c0000-631e1000	Deferred        secur32
PE	63480000-6348c000	Deferred        version
PE	637c0000-63869000	Deferred        urlmon
PE	63bc0000-63bda000	Deferred        shcore
PE	64a40000-64a94000	Deferred        shlwapi
PE	64ec0000-64fec000	Deferred        oleaut32
PE	65f40000-65f4c000	Deferred        kerberos
PE	66240000-66256000	Deferred        bcrypt
PE	663c0000-66472000	Deferred        winspool
PE	66500000-66513000	Deferred        msasn1
PE	66540000-6654a000	Deferred        atlthunk
PE	666c0000-666cf000	Deferred        hid
PE	66b00000-66b3d000	Deferred        win32u
PE	67840000-678b7000	Deferred        winepulse
PE	67d40000-67d6c000	Deferred        mmdevapi
PE	68500000-6855a000	Deferred        combase
PE	688c0000-688ea000	Deferred        netapi32
PE	69480000-694ad000	Deferred        mlang
PE	69540000-6958e000	Deferred        dinput8
PE	6a040000-6a062000	Deferred        msacm32
PE	6a280000-6a32c000	Deferred        msvcrt
PE	6a400000-6a534000	Deferred        ole32
PE	6ac80000-6ac87000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	6bc00000-6bc2c000	Deferred        sechost
PE	6bcc0000-6bd3f000	Deferred        setupapi
PE	6c740000-6c84c000	Deferred        cryptui
PE	6c940000-6c94b000	Deferred        sfc_os
PE	6c9c0000-6ca46000	Deferred        gdi32
PE	6cc40000-6cd9c000	Deferred        comctl32
PE	6d780000-6d7a8000	Deferred        ws2_32
PE	6d880000-6d890000	Deferred        msv1_0
PE	6de80000-6de88000	Deferred        api-ms-win-core-synch-l1-2-0
PE	6df00000-6df2f000	Deferred        shdocvw
PE	6e4c0000-6e4d6000	Deferred        dnsapi
PE	6e8c0000-6e995000	Deferred        crypt32
PE	6ed00000-6ef19000	Deferred        user32
PE	6f140000-6f148000	Deferred        api-ms-win-appmodel-runtime-l1-1-1
PE	6f480000-6f48b000	Deferred        nsi
PE	6f4c0000-6f4e8000	Deferred        wintrust
PE	70b40000-70c18000	Deferred        ucrtbase
PE	70d00000-70e08000	Deferred        comdlg32
PE	71200000-712f5000	Export          wininet
PE	74600000-747fb000	Deferred        iertutil
PE	7ac00000-7ac85000	Deferred        riched20
PE	7b000000-7b0eb000	Deferred        kernelbase
PE	7b600000-7b81d000	Dwarf           kernel32
PE	7bc00000-7bca2000	Dwarf           ntdll
PE	7e040000-7e044000	Deferred        winex11
Threads:
process  tid      prio (all id:s are in hex)
00000038 services.exe
	0000003c    0
	00000040    0
	0000004c    0
	00000050    0
	00000064    0
	00000080    0
	000000b0    0
	000000c4    0
	000000e4    0
00000044 svchost.exe
	00000048    0
	00000054    0
	00000058    0
0000005c winedevice.exe
	00000060    0
	00000068    0
	0000006c    0
	00000070    0
	00000074    0
	000000c0    0
00000078 winedevice.exe
	0000007c    0
	00000084    0
	00000088    0
	0000008c    0
	0000009c    0
	000000a0    0
	000000a4    0
00000094 explorer.exe
	00000098    0
	000000d0    0
	000000d4    0
000000a8 plugplay.exe
	000000ac    0
	000000b4    0
	000000b8    0
	000000bc    0
000000dc rpcss.exe
	000000e0    0
	000000e8    0
	000000ec    0
	000000f0    0
	000000f4    0
	000000f8    0
00000100 (D) Z:\home\mart\opt\flashpoint\data\FPSoftware\Flash\flashplayer_32_sa.exe
	00000104    0
	0000010c    0
	00000110    0
	00000114    0
	00000118    0
	0000011c    0
	00000120    0
	00000124    0
	00000128    0
	0000012c   15
	00000130    0 <==
	0000013c    0
System information:
    Wine build: wine-7.3
    Platform: i386 (WOW64)
    Version: Windows 7
    Host system: Linux
    Host version: 5.16.11-arch1-1
</pre></code>
</details>

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Flashpoint Version: Latest
 - Log text:
 ```
INFO  [10:16:34]                      002c:err:module:load_apiset_dll failed to load apiset: c0000482
INFO  [10:16:34]                      0034:err:module:load_apiset_dll failed to load apiset: c0000482
INFO  [10:16:34]                      003c:err:module:load_apiset_dll failed to load apiset: c0000482
INFO  [10:16:34]                      0048:err:module:load_apiset_dll failed to load apiset: c0000482
INFO  [10:16:34]                      0060:err:module:load_apiset_dll failed to load apiset: c0000482
INFO  [10:16:34]                      007c:err:module:load_apiset_dll failed to load apiset: c0000482
INFO  [10:16:34]                      0098:err:module:load_apiset_dll failed to load apiset: c0000482
INFO  [10:16:34]                      00ac:err:module:load_apiset_dll failed to load apiset: c0000482
INFO  [10:16:34]                      0024:err:module:load_apiset_dll failed to load apiset: c0000482
INFO  [10:16:34]                      00cc:err:module:load_apiset_dll failed to load apiset: c0000482
INFO  [10:16:34]                      00e0:err:module:load_apiset_dll failed to load apiset: c0000482
INFO  [10:16:34]                      0104:err:module:load_apiset_dll failed to load apiset: c0000482
INFO  [10:16:34]                      <Game> exited with signal null
INFO  [10:16:34]                      0108:fixme:ver:GetCurrentPackageId (0272FEF0 00000000): stub
INFO  [10:16:34]                      0108:fixme:ntdll:EtwEventActivityIdControl 0x1, 0272FE60: stub
INFO  [10:16:35]                      0104:fixme:pulse:pulse_channel_map_to_channel_mask Unhandled channel aux0
INFO  [10:16:35]                      0104:fixme:pulse:pulse_channel_map_to_channel_mask Unhandled channel aux1
INFO  [10:16:35]                      0104:fixme:pulse:pulse_channel_map_to_channel_mask Unhandled channel aux0
INFO  [10:16:35]                      0104:fixme:pulse:pulse_channel_map_to_channel_mask Unhandled channel aux1
INFO  [10:16:35]                      012c:fixme:sync:SetWaitableTimerEx (00000148, 054CFE80, 0, 00000000, 00000000, 00000000, 5) semi-stub
INFO  [10:16:35]                      wine: Call from 7BC2A3C0 to unimplemented function urlmon.dll.414, aborting
INFO  [10:16:35]                      wine: Unimplemented function urlmon.dll.414 called at address 7BC2A3C0 (thread 0130), starting debugger...
INFO  [10:16:35]                      0098:fixme:imm:ImeSetActiveContext (0x25ece0, 0): stub
INFO  [10:16:35]                      0098:fixme:imm:ImmReleaseContext (0000000000010020, 000000000025ECE0): stub
INFO  [10:16:35]                      0104:fixme:imm:ImeSetActiveContext (0x1413ec0, 1): stub
INFO  [10:16:35]                      0104:fixme:imm:ImmReleaseContext (00010062, 01413EC0): stub
INFO  [10:16:35]                      0138:err:module:load_apiset_dll failed to load apiset: c0000482
INFO  [10:16:35]                      0138:fixme:imm:ImeSetActiveContext (0x23f5b8, 1): stub
INFO  [10:16:35]                      0138:fixme:imm:ImmReleaseContext (0001008A, 0023F5B8): stub
INFO  [10:18:34]                      0148:err:module:load_apiset_dll failed to load apiset: c0000482
INFO  [10:18:34]                      0148:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
INFO  [10:18:34]                      0148:fixme:seh:WerSetFlags (2) stub
INFO  [10:18:34]                      0148:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
INFO  [10:18:34]                      0164:err:module:load_apiset_dll failed to load apiset: c0000482
INFO  [10:18:34]                      0164:fixme:heap:RtlSetHeapInformation 0000000000810000 0 000000000011F6B0 4 stub
INFO  [10:18:34]                      0164:fixme:seh:WerSetFlags (2) stub
INFO  [10:18:34]                      0164:fixme:heap:RtlSetHeapInformation 0000000000000000 1 0000000000000000 0 stub
INFO  [10:18:43]                      0140:err:ole:CoUninitialize Mismatched CoUninitialize
```

**Additional context**

**Comment by SSUPII** [comment]
[Wine 7.2]
I got it to work by replacing the projector to the original one and then
`winetricks winhttp` and `winetricks --force ie8`
the ie8 install will fail on a 64bit prefix, but before it actually tries to install ie8 enough is done to fix urlmon.dll
I just tested the games booting, so this needs testing.

**Comment by SSUPII** [comment]
This issue hasn't been resolved nor tested upon. I don't see why it should be closed.

**Comment by Martmists-GH** [comment]
I used your solution and it worked just fine, hence why I closed it.
