### ISSUE TITLE
[BUG] Linux Version: Couldn't start debugger

### ISSUE THREAD

**Issue by nimafanniasl** [FlashpointProject/launcher#320]
**Describe the bug**
I can't Play Games, when i click on the play button this happens in Logs:
INFO  [13:15:44]          Windows RG: Windows RG has been started
INFO  [13:15:44]       Game Launcher: Launch Game "Windows RG" (PID: 12574) [
                                    applicationPath: "FPSoftware\Flash\flashplayer_32_sa.exe",
                                    launchCommand:   "http://localflash/windowsrg.swf",
                                    command:         "wine start /unix "/home/nima/.flashpoint/data/FPSoftware/Flash/flashplayer_32_sa.exe" http://localflash/windowsrg.swf" ]
INFO  [13:15:47]          Windows RG: Windows RG exited with signal null
INFO  [13:15:48]                      wine: Unhandled exception 0x80000003 in thread f8 at address 7BC52E88 (thread 00f8), starting debugger...
INFO  [13:15:48]                      00f8:err:seh:start_debugger Couldn't start debugger L"winedbg --auto 244 96" (2)
INFO  [13:15:48]                      Read the Wine Developers Guide on how to set up winedbg or another debugger

**To Reproduce**
1. Go to Games
2. Click on any Flash Game (Like windows RG)
3. Click on Play
4. See error in logs

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Flashpoint Version 10.1.1

**Comment by n0samu** [comment]
This is a problem with Wine, not with Flashpoint Launcher. Feel free to join the #flashpoint-mac-linux-help channel in our Discord server to get help troubleshooting Wine.
