### ISSUE TITLE
[Feature Request]  Have a setting where MAD4FP can download from the Wayback Machine

### ISSUE THREAD

**Issue by qfoxb** [FlashpointProject/launcher#323]
This'd be super useful for now-defunct sites and games that aren't hosted either in the original format or aren't hosted at all

**Describe the solution you'd like**
Have a check box somewhere to have MAD4FP download from The Wayback Machine and you can supply a date/time to download it from

**Describe alternatives you've considered**
Have it auto detect web.archive.org links and have them use the _if flag on the date to remove the wayback machine header

**Additional context**
Wayback machine header can be removed by adding if_ to the end of the date

**Comment by n0samu** [comment]
1. This is already possible using Wayback Download Mode: https://bluemaxima.org/flashpoint/datahub/Downloading_from_Wayback#Using_Wayback_Download_Mode. However, it needs to be updated for Flashpoint Core 11.
2. As explained in the article above, the `id_` prefix should be used, *not* `if_`.
3. MAD4FP is really a function of [Flashpoint Router](/FlashpointProject/Flashpoint-Router), not the launcher. This issue isn't really relevant to this repo.
