### ISSUE TITLE
[BUG] White pixels all over screen on Some NVIDIA Cards

### ISSUE THREAD

**Issue by qfoxb** [FlashpointProject/launcher#324]
**Describe the bug**
Whenever I start the flashpoint launcher, there's an issue with some nvidia cards that causes white pixels to appear all over the screen
it's worstened by shaking the window

**To Reproduce**
1. Open Flashpoint
2. Shake Screen

**Expected behavior**
No white pixels on the screen, I shouldn't have to switch to compatibility mode just to make flashpoint usable

**Screenshots**
![image](https://user-images.githubusercontent.com/42038239/161451613-b1f3ace0-ca13-41d5-b90f-5e1e96c54363.png)
![gif](https://user-images.githubusercontent.com/42038239/161451784-f3b96695-5753-4c80-af40-850a2c6134e7.gif)

**Desktop (please complete the following information):**
 - OS: Windows 11 (Occured on windows 10 as well)
 - Flashpoint Version: 10.1.0.6
 - Graphics Card: NVIDIA GeForce 1060 6GB (GIGABYTE)
 - Log text (if relevant)

**Additional context**
Changing the compatibility mode (Anything before windows 8) seems to fix this

**Comment by n0samu** [comment]
Already fixed, see #295. A fixed build of the launcher hasn't been released yet though.

**Comment by qfoxb** [comment]
Closing as duplicate
