### ISSUE TITLE
[BUG] Launching game via Random Picks doesn't download GameZIP

### ISSUE THREAD

**Issue by n0samu** [FlashpointProject/launcher#331]
**Describe the bug**
When launching a game via the Random Picks on the Home tab, the game will not be downloaded first if it hasn't been downloaded yet. Flashpoint will immediately try to mount the game, which fails because the GameZIP is not present.

**To Reproduce**
1. Click the Home tab
2. Double-click a zipped game that hasn't been downloaded yet
3. The Flash Player will show a white screen (or the browser will show an error, etc)

**Expected behavior**
The GameZIP should be downloaded before the game launches, just like what happens when clicking the Download button to launch a game on the Games tab.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Flashpoint Version: 10.1.0.6 Infinity

**Comment by colin969** [comment]
Can you make sure this happens on the latest version

**Comment by n0samu** [comment]
Seems to be fixed in the new version, thanks!
