### ISSUE TITLE
[BUG] Clicking links on the About tab crashes the launcher

### ISSUE THREAD

**Issue by n0samu** [FlashpointProject/launcher#334]
**Describe the bug**
When I click the "Website", "Discord", or "GitHub" links on the launcher's About tab, the link opens, but then the launcher crashes.

**Expected behavior**
The links should open and the launcher should stay open instead of crashing.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Flashpoint Version: 10.1 Infinity

**Additional context**
The same bug occurred in the past when clicking the "Check out our planned features!” link on the homepage, but that was fixed. I guess we need the same fix here.

**Comment by colin969** [comment]
Fixed in d85da2b2ffc632df47d9d82dab30915781aaed6a
