### ISSUE TITLE
[Feature Request] Add a feature or option to put on different hard drives program/launcher and the data/games.

### ISSUE THREAD

**Issue by pabdani** [FlashpointProject/launcher#346]
Hi! I want to suggest a idea for Flashpoint.

## Definition: 
Make a feature or option to have parts of the program itself on different hard drives or locations.

## Explanation: 
I want to put my Flashpoint's launcher (on a SSD) and the games and data itself on a separate hard drive, because I want to save some space for other programs on my SSD and then Flashpoint runs smoothly on my PC.

## Practical example:
**Flashpoint's launcher:** SSD (then Flashpoint will run smooth)
**Flashpoint's games, data, savings, etc:** Other hard drive.

Thanks!

(sorry, I'm new to contributing on GitHub)

**Comment by n0samu** [comment]
This is already possible, just follow these steps:
1. Move Flashpoint's Launcher folder to your SSD, then open the launcher.
2. Click the Config tab, then click the "Browse" button next to the "Flashpoint Path" box.
3. Select your main Flashpoint folder.
4. Scroll down and click the "Save and Restart" button, and Flashpoint should work fine.
Keep in mind though that much of the speed of the launcher is determined by how fast it can read its database, which is stored in Flashpoint's `Data` folder (not the main folder). So moving the launcher to your SSD may not improve the speed as much as you hope. Let us know!
