### ISSUE TITLE
[Feature Request] Store playlists outside of flashpoint.sqlite

### ISSUE THREAD

**Issue by WumboSpasm** [FlashpointProject/launcher#354]
**Is your feature request related to a problem? Please describe.**
Storing playlists in the same database file as the launcher's games and animations has made manually updating Flashpoint a far more cumbersome task than it needs to be, and prevents the Ultimate updater (and any potential Infinity updater) from being truly hassle-free.

**Describe the solution you'd like**
Store playlists as individual files in the Data\Playlists directory like they were before. Instead of using XML, however, they should use the JSON format for parity with the configuration files and exported playlists.

**Comment by n0samu** [comment]
In a similar vein, I'd like to see tag filters stored in a separate JSON file (perhaps Data\tagFilters.json). They take up so much space in preferences.json right now, which doesn't feel like logical organization to me.

**Comment by skiesofravens** [comment]
Exists as of 12
