### ISSUE TITLE
[BUG] Search bar becomes unselectable

### ISSUE THREAD

**Issue by n0samu** [FlashpointProject/launcher#362]
**Describe the bug**
After the "No working Sources are available for this GameData" message pops up and is dismissed, the search bar becomes unselectable and cannot be typed into. Unfocusing and refocusing the launcher window fixes the issue.

**To Reproduce**
1. Select a game that doesn't have any GameData Sources available and click Download.
2. Click OK to dismiss the "No working Sources are available for this GameData" message.
3. It is now possible to interact with the launcher window again, but the search bar still cannot be selected or typed into.

**Expected behavior**
After dismissing the popup message, it should be possible to type into the search bar.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Launcher version: 10.1.3 (2022-07-22)

**Comment by colin969** [comment]
This is an issue with window focus on alerts on Windows. 

I've addressed it with a custom alert function, will appear alongside the Curate changes.
