### ISSUE TITLE
[BUG] Deal or no Deal (by Pacdude games) release date is much earlier

### ISSUE THREAD

**Issue by Zorklis** [FlashpointProject/launcher#393]
**Describe the bug**
 https://web.archive.org/web/20070320024839/http://pacdudegames.com/games/
Despite being listed with the Y8 publishing date, the game Deal or no Deal must've come out earlier per their index of games which was archived on March 20, 2007.
Original Date listed for it is February 27, 2006.
Non-original (Y8 upload) that is listed on flashpoint is 02 Jan 2007. 
Almost a year.
Hope this helps fix it

**Comment by n0samu** [comment]
Hi, I've updated the game's release date. This is not the right place to report game issues though. This is only for issues with the Flashpoint Launcher application.

**Comment by Zorklis** [comment]
I am aware but I think at the time (and it probably still is) it was hard to submit a report because of all requirements needed for a form? Or something to that, anyways thanks
