### ISSUE TITLE
ultra lite version of flash point

### ISSUE THREAD

**Issue by moongazer07** [FlashpointProject/launcher#396]
having a ultra lite version of flash point would be a good idea
how to make it ultra lite
games do not come pre installed
only the flashpoint emulator software
user will have to download games  manually

**Comment by geocine** [comment]
Have you tried the software? That is how it behaves right now if you use the `Infinity` version. The reason why its still 2.9 GB is due to the runtime files needed not because of games being preinstalled. You should try it out.
