### ISSUE TITLE
Cannot open my own swf files [BUG]

### ISSUE THREAD

**Issue by WolfyRed** [FlashpointProject/launcher#397]
**Describe the bug**
I want to try to test my own swf files in the launcher, but I cannot find a way to do it.

**To Reproduce**
1. check all around for import button
2. find nothing

**Expected behavior**
Being able to import the swf files to play other downloaded swf games

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Flashpoint Version 11.1

**Comment by skiesofravens** [comment]
This is not a bug, open the .swf with a projector in the FPSoftware\Flash folder. And if you want to open them explicitly within Flashpoint, like if it has a sitelock and requires a specific domain, that is what the [curate menu](https://flashpointarchive.org/datahub/Curation_Tutorial) is for.
