### ISSUE TITLE
[BUG] Can't open any games at all with the Launcher

### ISSUE THREAD

**Issue by AzhamProdLive** [FlashpointProject/launcher#402]
**Describe the bug**
After installing the launcher from the website, I try to start a game like Bejeweled

**To Reproduce**
1. Open the launcher with ./Flashpoint
2. Click on any games you want to play
3. Wait a little like the "Please wait" tells us to do
4. See briefly (0.5 seconds prolly) the stop button and gets back to Play, and nothing happened

**Expected behavior**
Game should start and show up

**Screenshots**
None, because there is no error code whatsoever in the terminal.

**Desktop (please complete the following information):**
 - OS: Arch Linux with WM (BSPWM) 
 - Flashpoint Version 11 Infinity
 - Log text : No errors are shown, which is weird

**Additional context**
I downloaded the Launcher today thanks to the guide given here > https://flashpointarchive.org/datahub/Linux_Support , I restarted my computer, tried reinstalling it, and still got no fixes

**Comment by colin969** [comment]
Linux support is provided via the discord server
