### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by RayDog1995** [FlashpointProject/launcher#419]
**Describe the solution you'd like**

Can you turn this into a container, that way its web accessible

**Describe alternatives you've considered**

I have not

**Additional context**

**Comment by prostagma-fp** [comment]
We have an experimental frontend that includes a Docker setup: https://github.com/Dri0m/9o3o
Not exactly using the launcher's code though.

**Comment by colin969** [comment]
Bit late to answer, but this isn't really possible. Games have to run on the same machine, and a web setup is only useful if you can pipe all input and display through the web client.

This simply isn't possible. You're better off using something like Parsec into a machine running it.
