### ISSUE TITLE
[Request] Add labels for operating system specific issues

### ISSUE THREAD

**Issue by foxtrotdev** [FlashpointProject/launcher#432]
**Is your feature request related to a problem? Please describe.**
I'm frustrated because there are no labels showing which operating system (OS) a problem is related to, making it hard to know which OS the issue affects.

**Describe the solution you'd like**
I would like the repository to have labels that specify the OS (e.g., Windows, macOS, Linux) for each issue.

**Describe alternatives you've considered**
Another option could be to mention the OS in the title or description of each issue, but labels would be more efficient.

**Additional context**
Adding OS-specific labels will make it easier to identify and fix problems by clearly showing which OS is involved.

**Comment by colin969** [comment]
Done 👍
