### ISSUE TITLE
[BUG] Keyboard shortcuts for zooming in and out don't work as expected

### ISSUE THREAD

**Issue by n0samu** [FlashpointProject/launcher#437]
**Describe the bug**
The `Ctrl -` keyboard shortcut reduces the launcher's zoom level, but `Ctrl +` does not zoom in unless the Shift key is held down. I guess that makes sense because you need to hold the shift key to type the + character, but this is inconvenient and goes against the convention used in other apps.

Also, when you zoom in and out using the keyboard shortcuts, the restrictions of the zoom bar are not enforced. So you can keep zooming out to under 40% and keep zooming in to over 160%. Worse, if you zoom out too far, the launcher crashes.

**Expected behavior**
- `Ctrl +` should zoom in; you shouldn't need to hold the Shift key.
- You shouldn't be able to use keyboard shortcuts to set the zoom level outside the normal limits (40% to 160%).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Flashpoint Version: 13

**Comment by dot-mike** [comment]
I'm not able reproduce this issue. Keybind `ctrl +` works for me on Windows.

**Comment by n0samu** [comment]
I'm using a laptop keyboard with the same layout as this one: https://laptopkeys.com/uploads/2132_1495763532_M123.jpg
Notice that the only way to type the `+` character on this keyboard is to hold shift while pressing the `=` key.

**Comment by dot-mike** [comment]
https://github.com/FlashpointProject/launcher/pull/449
