### ISSUE TITLE
[BUG] Hard reload ctrl+shfit+r does not reload extensions

### ISSUE THREAD

**Issue by dot-mike** [FlashpointProject/launcher#441]
**Describe the bug**
When testing extensions it would be handy to reload by refreshing the Electron app by presisng the combination ctrl+shift+r which is a shortcut for reloading the Electron-window

**To Reproduce**
1. Add extensions
2. Start Launcher
3. Make changes to extensions
4. Edit extensions, i.e add new console.log command
5. Changes not applied

**Expected behavior**
Extensions should be executed as if it was a fresh start of the application when doing reload.

**Additional context**
Useful for when testing and developing extensions. "Everything else" in the window is reloaded, so I expect extensions to have the same behavior.

**Comment by dot-mike** [comment]
This can be a continuation of 9d9b3d0. I'll see if I can work on this.

**Comment by colin969** [comment]
Ctrl+Shift+R is more for testing cosmetic changes. The backend does not reload.

You can unload and reload extensions, there are (rarely) used functions for that I wrote I believe, and I'm fine having it extend to that.

**Comment by colin969** [comment]
This is a good reference point

https://github.com/FlashpointProject/launcher/blob/9e768b23ed1bb025e6342863841d263e74127879/src/back/extensions/ApiImplementation.ts#L73
