### ISSUE TITLE
Server inconsistently fails to start

### ISSUE THREAD

**Issue by BlueMaxima** [FlashpointProject/launcher#84]
Running the launcher via the usual shortcut or directly will sometimes, not always, fail to launch the server. The server shows the error message of ServerRoot not being a valid directory and an exit code of 1 on the Developer tab. Restarting the server immediately via the Restart button on the Developer tab will make the server work fine. I haven't been able to make the issue occur consistently, although it may be affected by not opening Flashpoint for some time.

**Comment by TBubba** [comment]
This issue has been resolved some time ago by making the server restart automatically when it fails unexpectedly.
