### ISSUE TITLE
Starting and stopping the launcher messes up the proxy settings in Windows 10.

### ISSUE THREAD

**Issue by Agasd** [FlashpointProject/launcher#87]
Whenever I start or stop the launcher my internet stops working even after reboot. The only solution is to turn on and off proxying in the settings.

**Comment by TBubba** [comment]
Hey! Sorry for not responding for so long.

We are no longer relying on the Redirector which is probably what caused your problem. If you're still having trouble feel free to open a new issue or reach us on Discord. I promise to reply quicker next time! 😉
