### ISSUE TITLE
Translation for 'zh-cn'(90% without curate)

### ISSUE THREAD

**Issue by feihu233** [FlashpointProject/launcher#89]
{
  "name": "简体中文",
  "config": {
    "configHeader": "设置",
    "configDesc": "(你必须点击'保存&重启'来使部分设置生效)",
    "preferencesHeader": "首选项",
    "extremeGames": "成人游戏",
    "extremeGamesDesc": "显示含有色情，暴力或其他不适合儿童的元素的游戏",
    "enableEditing": "启用编辑",
    "enableEditingDesc": "启用对游戏，其他应用程序和播放列表的编辑，也显示'Curate'标签",
    "currentLanguage": "首选语言",
    "currentLanguageDesc": "将哪种语言作为主要显示语言",
    "fallbackLanguage": "第二语言",
    "fallbackLanguageDesc": "若首选语言不可用，则选用第二语言显示",
    "auto": "自动 ({0})",
    "none": "否/无",
    "flashpointHeader": "Flashpoint",
    "flashpointPath": "Flashpoint路径",
    "flashpointPathDesc": "Flashpoint文件夹路径 (可被关联)",
    "browse": "浏览",
    "redirector": "重定向器",
    "redirectorFiddler": "游荡者(Fiddler)",
    "redirectorDesc": "使用哪个软件将游戏流量重定向到本地网络服务器，在Linux上不适用",
    "platforms": "平台",
    "nativePlatforms": "本地平台",
    "nativePlatformsDesc": "使用这些平台的本地版本，如不可用，将使用Wine",
    "visualsHeader": "视觉化",
    "useCustomTitleBar": "使用自定义标题栏",
    "useCustomTitleBarDesc": "使用此窗口顶部的自定义标题栏",
    "theme": "主题",
    "noTheme": "无主题",
    "themeDesc": "主题文件路径(在Theme文件夹内)",
    "advancedHeader": "高级",
    "showDeveloperTab": "显示开发者标签",
    "showDeveloperTabDesc": "显示'开发人员'选项卡，只对开发者及管理员有用",
    "saveAndRestart": "保存&重启"
  },
  "home": {
    "updateHeader": "启动器更新",
    "currentVersion": "当前版本",
    "nextVersion": "最新版本",
    "updateAvailable": "升级可用",
    "upToDate": "最新更新",
    "downloadingUpdate": "正在下载更新...",
    "quickStartHeader": "快速启动",
    "hallOfFameInfo": "只想找最好的？请看: {0}",
    "hallOfFame": "名人堂",
    "allGamesInfo": "寻找游戏: {0}",
    "allGames": "全部游戏",
    "allAnimationsInfo": "观赏视频: {0}.",
    "allAnimations": "全部动画",
    "configInfo": "启动器选项修改: {0}",
    "config": "设置",
    "helpInfo": "获取帮助: {0}",
    "help": "ReadMe帮助文档",
    "upgradesHeader": "升级",
    "installComplete": "全部下载(279G以上，确保有足够空间)",
    "alreadyInstalled": "已下载",
    "download": "下载",
    "update": "更新/升级",
    "checkingUpgradeState": "检查更新状态...",
    "extrasHeader": "Extras",
    "favoritesPlaylist": "收藏/最爱播放列表",
    "tagList": "标签列表",
    "filterByPlatform": "按平台筛选",
    "plannedFeatures": "查看计划更新的功能！",
    "notesHeader": "注: ",
    "notes": "若有问题(issue)，建议首先查看ReadMe帮助文档",
    "linuxSupport": "关于Linux的问题(issue)？ {0}",
    "linuxSupportLinkText": "FAQ",
    "randomPicks": "随机游戏"
  },
  "logs": {
    "filters": "筛选器",
    "copyText": "复制文本",
    "clearLog": "清除日志(Log)"
  },
  "app": {
    "home": "主页",
    "browse": "浏览",
    "logs": "日志",
    "config": "设置",
    "about": "关于",
    "curate": "Curate",
    "developer": "开发者",
    "searchPlaceholder": "搜索...",
    "hideRightSidebar": "隐藏右边栏",
    "showRightSidebar": "显示右边栏",
    "hideLeftSidebar": "隐藏左边栏",
    "showLeftSidebar": "显示左边栏",
    "total": "全部",
    "newGame": "新游戏",
    "list": "列表",
    "grid": "网格",
    "searchResults": "搜索结果"
  },
  "filter": {
    "dateAdded": "添加日期",
    "tags": "标签",
    "platform": "平台",
    "series": "系列",
    "title": "标题",
    "developer": "开发者",
    "publisher": "发布者",
    "ascending": "上升(Ascending)",
    "descending": "下降(Descending)"
  },
  "developer": {
    "developerHeader": "开发者",
    "developerDesc": "以下为所有可用的开发者工具",
    "checkMissingImages": "检查丢失图像",
    "checkMissingImagesDesc": "列出所有无缩略图或屏幕截图的游戏",
    "checkGameIds": "检查游戏ID",
    "checkGameIdsDesc": "列出所有ID重复或无效的游戏",
    "checkGameTitles": "检查游戏标题",
    "checkGameTitlesDesc": "列出同平台所有标题重复的游戏",
    "checkGameFields": "Check Game Fields",
    "checkGameFieldsDesc": "列出所有具有空字段的游戏(或不应为空字段的游戏)",
    "checkPlaylists": "检查播放列表",
    "checkPlaylistsDesc": "列出所有ID重复/无效的播放列表，或所有含有ID缺失/无效的游戏的播放列表",
    "checkGameFileLocation": "检查游戏文件位置",
    "checkGameFileLocationDesc": "列出所有带有无法解析为文件路径的启动命令的游戏(这与'打开文件位置'功能有关，与启动游戏无关)",
    "checkMissingExecMappings": "检查缺少的Exec映射",
    "checkMissingExecMappingsDesc": "列出Win32，Linux和Darwin的所有缺少EXEC映射的唯一EXEC",
    "renameImagesTitleToId": "重命名图像 (标题 -> ID)",
    "renameImagesTitleToIdDesc": "查找文件名中包含游戏标题的所有游戏图像，并将其用ID重命名",
    "renameImagesIdToTitle": "重命名图像 (ID -> 标题)",
    "renameImagesIdToTitleDesc": "查找文件名中包含游戏ID的所有游戏图像，并将其用标题重命名",
    "createMissingFolders": "创建缺少的文件夹",
    "createMissingFoldersDesc": "在Flashpoint文件夹结构中查找所有缺少的文件夹并创建它们",
    "servicesHeader": "后台服务",
    "servicesMissing": "无后台服务",
    "running": "运行中",
    "stopped": "已停止",
    "killing": "终止中",
    "start": "启动",
    "startDesc": "启动服务",
    "stop": "停止",
    "stopDesc": "停止运行中服务",
    "restart": "重启",
    "restartDesc": "重启服务",
    "details": "详细信息",
    "detailsDesc": "打开包含服务(service)详细信息的对话框(dialog)"
  },
  "about": {
    "aboutHeader": "关于",
    "flashpoint": "BlueMaxima's Flashpoint",
    "flashpointDesc": "这个启动器是为保护Flash项目而建立的，志在成为基于网络的Flash游戏博物馆",
    "website": "网站",
    "flashpointLauncher": "Flashpoint启动器",
    "flashpointLauncherDesc": "一个开源桌面应用程序，用于浏览，管理和游玩Flashpoint中的游戏",
    "version": "版本",
    "license": "声明 (License)",
    "licenseInfo": "MIT (详请阅读'LICENSE'文件)",
    "creditsHeader": "创作者名单(Credits)"
  },
  "browse": {
    "noTitle": "无标题",
    "by": "by",
    "noDeveloper": "无开发者",
    "alternateTitles": "副标题",
    "noAlternateTitles": "无副标题",
    "tags": "标签",
    "noTags": "无标签",
    "series": "系列",
    "noSeries": "无系列",
    "publisher": "发布者",
    "noPublisher": "无发布者",
    "source": "源 Source",
    "noSource": "无源 Source",
    "platform": "平台",
    "noPlatform": "无平台",
    "playMode": "游戏模式",
    "noPlayMode": "无游戏模式",
    "status": "状态",
    "noStatus": "无状态",
    "version": "版本",
    "noVersion": "无版本",
    "releaseDate": "发布日期",
    "noReleaseDate": "无发布日期",
    "language": "语言",
    "noLanguage": "无语言",
    "dateAdded": "添加日期",
    "brokenInInfinity": "已损坏(无穷大)",
    "extreme": "成人",
    "playlistNotes": "播放列表备注",
    "noPlaylistNotes": "无备注",
    "notes": "备注",
    "noNotes": "无备注",
    "originalDescription": "原始描述",
    "noOriginalDescription": "无原始描述",
    "additionalApplications": "其他应用程序",
    "noName": "无名称",
    "launch": "启动",
    "autoRunBefore": "Auto Run Before",
    "waitForExit": "等待或退出",
    "applicationPath": "应用程序路径",
    "noApplicationPath": "无应用程序路径",
    "launchCommand": "启动命令",
    "noLaunchCommand": "无启动命令",
    "library": "库",
    "defaultLibrary": "初始库",
    "thumbnail": "Thumbnail",
    "screenshot": "截图",
    "dropImageHere": "拖动到此区域来添加图片",
    "noGameSelected": "无被选择的游戏",
    "clickToSelectGame": "单击游戏以选择",
    "failedToLoadPlaylistFolder": "加载播放列表(PlayList)文件夹失败",
    "checkLogForInfo": "查看日志(log)以获取详细信息",
    "loadingPlaylists": "加载播放列表(PlayList)中...",
    "deleteAdditionalApplication": "删除其他应用程序",
    "deleteGameAndAdditionalApps": "删除游戏(及其他应用程序)",
    "removeGameFromPlaylist": "从播放列表(PlayList)移除游戏",
    "saveChanges": "保存更改",
    "discardChanges": "取消更改",
    "editGame": "编辑/修改游戏",
    "allGames": "全部游戏",
    "newPlaylist": "新播放列表(PlayList)",
    "emptyPlaylist": "空播放列表(Playlist)",
    "noGamesFound": "未找到游戏！",
    "dropGameOnLeft": "将游戏拖到此处{0}以添加",
    "leftSidebar": "左边栏",
    "setFlashpointPathQuestion": "你是否在{1}页上设置了{0}的路径？",
    "flashpointPath": "Flashpoint路径",
    "config": "设置",
    "noteSaveAndRestart": "注: 你必须按{0}才能使更改生效",
    "saveAndRestart": "保存&重启",
    "loadingGames": "加载游戏中...",
    "thereAreNoGames": "无游戏",
    "noGameMatchedDesc": "无匹配的游戏标题",
    "noGameMatchedSearch": "请尝试截短搜索词汇"
  },
  "curate": {
    "importAll": "全部导入",
    "importAllDesc": "导入所有当前加载的curations",
    "deleteAll": "全部删除",
    "deleteAllDesc": "删除所有当前加载的curations",
    "saveImportedCurations": "保存导入的Curations",
    "openCurationsFolder": "Curations文件夹",
    "openCurationsFolderDesc": "在资源管理器中打开Curations文件夹",
    "openExportsFolder": "导出Curations",
    "openExportsFolderDesc": "打开包含导出Curations的默认Exports文件夹Open the default Exports folder containing your exported curations.",
    "openImportedFolder": "导入Curations",
    "openImportedFolderDesc": "Open the default Imported curations folder containing your imported curations.",
    "newCuration": "New Curation",
    "newCurationDesc": "Creates a new curation with a unique folder",
    "loadMeta": "Load Meta",
    "loadMetaDesc": "Load one or more Curation meta files",
    "loadArchive": "Load Archive",
    "loadArchiveDesc": "Load one or more Curation archives",
    "loadFolder": "Load Folder",
    "loadFolderDesc": "Load one or more Curation folders",
    "noCurations": "No Curations",
    "id": "Curation Folder",
    "heading": "Heading",
    "noHeading": "No Heading",
    "folderName": "Extras Folder",
    "noFolderName": "No Folder Name",
    "message": "Launch Message",
    "noMessage": "No Message",
    "curationNotes": "Curation Notes",
    "noCurationNotes": "No Curation Notes",
    "newAddApp": "New App",
    "addExtras": "Add Extras",
    "addMessage": "Add Message",
    "removeAddApp": "Remove App",
    "indexContent": "Refresh Content",
    "delete": "Delete",
    "deleteCurationDesc": "Delete this curation (Files can not be recovered)",
    "openFolder": "Open Folder",
    "run": "Run",
    "export": "Export",
    "import": "Import",
    "contentFiles": "Content Files",
    "warnings": "Warnings",
    "noLaunchCommand": "'Launch Command' is a required field. Please fill it in before importing.",
    "invalidLaunchCommand": "'Launch Command' does not fit these URL requirements:",
    "releaseDateInvalid": "'发布日期'格式必须遵循年-月-日(YYYY-MM-DD),其中月和日是可选项",
    "unusedApplicationPath": "'应用程序路径'有未使用的值，请确保拼写正确！",
    "unusedTags": "以下标签在任何其他游戏中都不存在，这些标签正确吗？",
    "unusedPlatform": "'平台'有未使用的值，请确保拼写正确！",
    "nonExistingLibrary": "'Library' is not the name of an existing library! (Default will be used)",
    "nonContentFolders": "Non-Content folders found in Curation folder. Are they supposed to be there?",
    "ilc_notHttp": "使用HTTP.",
    "ilc_nonExistant": "Point to an existing file in your curation's 'content' folder."
  },
  "playlist": {
    "enterDescriptionHere": "在此添加描述...",
    "noDescription": "无描述",
    "save": "保存",
    "saveDesc": "保存更改并退出编辑",
    "discard": "取消",
    "discardDesc": "取消更改并退出编辑",
    "delete": "删除",
    "deleteDesc": "删除播放列表(PlayList)",
    "areYouSure": "确定吗？",
    "noTitle": "无标题",
    "titlePlaceholder": "标题...",
    "noAuthor": "无作者",
    "authorPlaceholder": "作者...",
    "by": "by"
  },
  "misc": {
    "noBlankFound": "未找到{0}",
    "addBlank": "添加{0}",
    "deleteAllBlankImages": "删除该游戏所有共{0}张图片",
    "yes": "是",
    "no": "否",
    "downloading": "下载中",
    "extracting": "提取中(Extracting)",
    "installingFiles": "下载文件中...",
    "complete": "已完成"
  },
  "menu": {
    "viewThumbnailInFolder": "查看文件夹中的缩略图",
    "viewScreenshotInFolder": "查看文件夹中的截图",
    "openFileLocation": "打开文件位置",
    "duplicateMetaOnly": "复制(仅元数据(Meta))",
    "duplicateMetaAndImages": "复制(元数据(Meta)和图片)",
    "exportMetaOnly": "导出(仅元数据(Meta))",
    "exportMetaAndImages": "导出(元数据(Meta)和图片)"
  },
  "dialog": {
    "programNotFound": "项目未找到！",
    "phpNotFound": "在路径上未找到PHP，请检查是否安装？\n若未安装，您可能会遇到意外或损坏",
    "wineNotFound": "运行此游戏需要Wine\n详情请参阅Linux支持Wiki文章",
    "flashpointPathNotFound": "未设置Flashpoint文件夹或文件夹无效，是否立即另外选择文件夹？",
    "fileNotFound": "未找到文件！",
    "flashpointPathInvalid": "Flashpoint路径无效！",
    "pathNotFound": "找不到路径！",
    "selectFileToExportMeta": "选择要保存元数据(Meta)的文件",
    "selectFolderToExportMetaAndImages": "选择要保存元数据(meta)和图像的文件夹",
    "replaceFilesQuestion": "替换文件？",
    "exportedAlreadyExistsYesNo": "一个或多个导出的文件已存在\n是否替换？",
    "selectFolder": "选择文件夹",
    "selectScreenshot": "选择截图",
    "selectThumbnail": "选择缩略图",
    "selectThemeFile": "选择主题(Theme)文件",
    "selectCurationFolder": "选择Curation文件夹",
    "selectCurationArchive": "选择Curation Archive(s)",
    "selectCurationMeta": "选择Curation Meta(s)",
    "errorParsingPlatforms": "解析平台时出错！",
    "errorParsingPlatformsMessage": "解析平台XML时出现{0}个错误\n详细信息请查看日志(Log)",
    "dataRequired": "需要其他数据",
    "dataRequiredDesc": "你必须现在主页面上安装更新，然后才能使用启动程序\n\n是否立即执行此操作？",
    "upgradeWillInstallTo": "{0} 将安装于",
    "verifyPathSelection": "之后的升级也将安装于此，是否确定？",
    "restartNow": "现在重启？",
    "restartToApplyUpgrade": "重启之前不会应用更新，是否重启？",
    "areYouSure": "确定吗？"
  },
  "libraries": {
    "arcade": "游戏",
    "theatre": "动画"
  },
  "upgrades": {
    "infinity": "Flashpoint Infinity",
    "infinityDesc": "包含对Flash游戏的支持",
    "tech": "其他技术支持",
    "techDesc": "添加对其他技术的支持，如Shockwave，Unity，Java，H5等",
    "screenshots": "Logo及截图",
    "screenshotsDesc": "为所有网格试图添加Logo，为所有游戏添加截图"
  }
}

**Comment by colin969** [comment]
These should've been submitted via

https://crowdin.com/project/flashpoint-launcher/

I've submitted them on your behalf

**Comment by TBubba** [comment]
Closing this!
