### ISSUE TITLE
Linux version needed ;-)

### ISSUE THREAD

**Issue by abixadamj** [FlashpointProject/launcher#90]
How can I help to make linux version?

**Comment by Pastew** [comment]
It doesn't work with Linux, after installing additional dependencies?

```
Linux Dependencies
libgtk-3-0
libnss3
Install by running sudo apt install libgtk-3-0 libnss3
```

**Comment by abixadamj** [comment]
@Pastew - my fault, I did not look deep ;-) I Just read at https://bluemaxima.org/flashpoint/faq/ :
What operating systems do you support?
Windows 7 and up, as thoroughly updated as possible.
And because I sell computers to schools with Linux, I thought - great source, but why only for Windows?
I will try to install it on my Mint 19.3 in some free time to check. Maybe next week.

**Comment by colin969** [comment]
Linux support is dealt with under here

https://bluemaxima.org/flashpoint/datahub/Linux_Support

Sadly it's limited by whoever has the time to do it.

**Comment by colin969** [comment]
Collapsing into #120
