### ISSUE TITLE
Nothing works in infinity

### ISSUE THREAD

**Issue by Harp3rDev** [FlashpointProject/launcher#93]
I downloaded version 7.1 of infinity, and none of the games or animations load when I click them. Flash player comes up and doesn't load and then the redirector says it couldn't get the .swf file. I got infinity because my pc only has 15 gigabytes of storage and I would need a lot of space to get the full version.
![image](https://user-images.githubusercontent.com/51060508/75117114-9bcab100-563c-11ea-8548-87cc6be72944.png)

**Comment by colin969** [comment]
This isn't related to FPL.

If you're using Avast or AVG, check the wiki page

https://bluemaxima.org/flashpoint/datahub/Troubleshooting_Antivirus_Interference

Otherwise make sure you've read the extended FAQ

https://bluemaxima.org/flashpoint/datahub/Extended_FAQ

Or use the Discord

**Comment by Harp3rDev** [comment]
It might be my malware bytes antivirus might be causing it ill check it out later and tell you if it works.

**Comment by Harp3rDev** [comment]
It still gives me error 500 even though I pardoned the exe.

**Comment by colin969** [comment]
Please check if this is still relevant on latest release

**Comment by colin969** [comment]
Closed for inactivity
