### ISSUE TITLE
Request Linux 32 Bit version and Issues with Linux Support

### ISSUE THREAD

**Issue by patriciaa260** [FlashpointProject/launcher#95]
I see in [(https://bluemaxima.org/flashpoint/datahub/Linux_Support)] that there is only version for 64 bits and one for archlinux, not debian. **Please consider to make one version for Linux Debian 32 bits.**

I tried to emulate the windows version (Infinity) with Wine, but it doesn work.
Also I tried to install the latest package of Flashpoint [https://drive.google.com/file/d/1eai0nFWe0XNc8WbsIg-koOzLc7jk_b_k/view?usp=sharing].
It doesn work too - when openning the shortcut, nothing happens.

**Comment by colin969** [comment]
Collapsing into #120
